[package]
name = "keycli"
version = "0.1.0"
description = "typing test in the terminal"
authors = ["alaidine <aa.alimlinde@gmail.com>"]
license = "Apache 2.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = "0.29.0"
